### ISSUE TITLE
Could not find command "server".

### ISSUE THREAD

**Issue by GCorbel** [castwide/solargraph-utils#3]
I try to use solargraph with deoplete, with [depolete-solargraph](https://github.com/uplus/deoplete-solargraph). When I launch an autocompletion, I have this message : 
```
Traceback (most recent call last):
^@  File "/home/dougui/.vim/bundle/deoplete-solargraph/rplugin/python3/deoplete/source/solargraph.py", line 56, in start_server
^@    self.server = solar.Server()
^@  File "/home/dougui/.local/lib/python3.6/site-packages/solargraph_utils/core.py", line 19, in __init__
^@    self.start()
^@  File "/home/dougui/.local/lib/python3.6/site-packages/solargraph_utils/core.py", line 42, in start
^@    raise ServerError('Failed to startserver' + (output and ':\n' + output))
^@solargraph_utils.helpers.ServerError: Failed to start server:
^@Could not find command "server".
```

**Comment by GCorbel** [comment]
Sorry, it's the wrong project. I moved to : https://github.com/uplus/solargraph-utils.py/issues/4 .
